### ISSUE TITLE
`debops project init` sets wrong paths in ansible.cfg

### ISSUE THREAD

**Issue by imrejonk** [debops/debops#1902]
I was just trying out the new debops script by creating a new DebOps project:

`$ debops project init ~/tmp/debops`

This command also creates the ansible.cfg file, but it seems to contain incorrect paths to the DebOps installation directory. My DebOps installation is at ~/src/debops/debops.

in **library**: `~/src/debops/debops/src/debops/_data/ansible/collections/ansible_collections/debops/debops/plugins/modules` does not exist.

in **action_plugins**: `~/src/debops/debops/src/debops/_data/ansible/collections/ansible_collections/debops/debops/plugins/action` does not exist.

in **callback_plugins**: `~/src/debops/debops/src/debops/_data/ansible/collections/ansible_collections/debops/debops/plugins/callback` does not exist.

in **connection_plugins**: `~/src/debops/debops/src/debops/_data/ansible/collections/ansible_collections/debops/debops/plugins/connection` does not exist.

in **filter_plugins**: `~/src/debops/debops/src/debops/_data/ansible/collections/ansible_collections/debops/debops/plugins/filter` does not exist.

in **lookup_plugins**: `~/src/debops/debops/src/debops/_data/ansible/collections/ansible_collections/debops/debops/plugins/lookup` does not exist.

in **vars_plugins**: `~/src/debops/debops/src/debops/_data/ansible/collections/ansible_collections/debops/debops/plugins/vars` does not exist.

Upon running the `bootstrap` playbook I get this related error:
```
TASK [debops.debops.netbase : Manage entries in /etc/hosts] *********************************************
fatal: [powerdns.imrejonk.nl]: FAILED! => 
  msg: 'template error while templating string: no filter named ''parse_kv_config''. String: {{ netbase__combined_hosts | parse_kv_config }}'
```

I currently work around this issue by creating a symlink `ansible/plugins/filter` to `~/src/debops/debops/ansible/roles/ansible_plugins/filter_plugins`.

**Comment by imrejonk** [comment]
This also affects the site playbook:
```
ERROR! couldn't resolve module/action 'dpkg_divert'. This often indicates a misspelling, missing collection, or incorrect module path.
```
A workaround is to create a symlink `ansible/plugins/modules` to `~/src/debops/debops/ansible/roles/ansible_plugins/library`.

**Comment by drybjed** [comment]
Thanks for the bug report! Currently Ansible expects DebOps to behave like an Ansible Collection, which the repository is not yet converted to. I think that if you symlink the monorepo inside of the project directory at `debops/`, it should work normally.

On my end, I'll try to speed up the conversion of the monorepo to full Collection format to avoid this issue ASAP.

**Comment by imrejonk** [comment]
Symlinking the monorepo at `debops/` in the project directory doesn't work for me, I have to create these three symlinks in `ansible/plugins/` in order to succesfully run the bootstrap and common playbooks:

```
lrwxrwxrwx 1 imre imre 73 okt 31 13:17 filter -> /home/imre/src/debops/debops/ansible/roles/ansible_plugins/filter_plugins
lrwxrwxrwx 1 imre imre 73 okt 31 13:46 lookup -> /home/imre/src/debops/debops/ansible/roles/ansible_plugins/lookup_plugins
lrwxrwxrwx 1 imre imre 66 okt 31 13:40 modules -> /home/imre/src/debops/debops/ansible/roles/ansible_plugins/library
```

**Comment by drybjed** [comment]
This issue should be solved by the https://github.com/debops/debops/pull/1903 PR. @imrejonk, can you test when it passes the tests and gets merged?

**Comment by imrejonk** [comment]
Works! Thanks for the fix. I'm still seeing incorrect action_plugins and vars_plugins paths though, is that expected?

**Comment by drybjed** [comment]
If you installed DebOps scripts with `pip3 install --editable ~/src/debops/debops`, then the `~/src/debops/debops/src/debops/_data/ansible/collections/ansible_collections/debops/debops/plugins/vars` and similar paths are correct. They point to the `ansible/plugins/` directories that are inside "DebOps Collection", which is effectively in `ansible/collections/ansible_collections/debops/debops/` directory of the monorepo. However, this path is taken from the Python package data, which is located in `src/debops/_data/` directory in the monorepo.

**Comment by imrejonk** [comment]
Ah right, I see that we currently don't include any action or vars plugins in the DebOps collection, so that shouldn't be a problem. I'm closing this issue.

ansible/plugins now contains duplicated files:
```
./callback_plugins/profile_tasks.py
./callback/profile_tasks.py
./connection/lxc_ssh.py
./connection_plugins/lxc_ssh.py
```
I think we can get rid of the `callback_plugins` and `connection_plugins` directories, correct?

**Comment by drybjed** [comment]
Yes, I will remove them on the next pass.
